### PR TITLE
Fix four bugs, mostly involving use of custom bin annotations

### PR DESCRIPTION
**Pull request by ilarischeinin**
Fixes a total of four bugs, mostly involving situations where custom bin annotations are used.

1. When a numerical value is used for parameter residual of applyFilters(), it should (according to manual pages) correspond to "the cutoff as number of standard deviations estimated with madDiff". However, instead of multiplying the supplied parameter value with the calculated standard deviation, the parameter value was used directly. This is now fixed. When a boolean value was used for the parameter (the default is TRUE), everything was fine. In practice, the bug only affected situations with custom-made bin annotations.

2. Same as above, but for highlightFilters().

3. When using the residual filter, applyFilters() used to remove chromosomes for which the filter was missing altogether (for the pre-generated bin annotations this meant X and Y). This was changed a while ago, but highlightFilters() still followed the old behavior. This is now fixed. Out of the four bugs, this is the only one that has an effect when using pre-generated bin annotations.

4. When an annotation package was present, it blocked the possibility to load other bin annotations for the same genome build via the path parameter. This is now fixed.

Also a couple of other small changes. Because of the bug fixes, this should be incorporated to both the development and release versions of Bioconductor. It could make sense though to first merge with development, and after a bit more/wider testing, to do the same with the release.

### CODE REVIEW

**Comment by ilarischeinin** [comment]
By the way, due to the problems in using CGHcall with individual and/or non-cancer samples, I have also implemented a simple [cutoff-based calling](https://github.com/ilarischeinin/QDNAseq/tree/cutoff-calling). To be integrated a bit later.

**Comment by ilarischeinin** [comment]
Added one more bug fix.

**Comment by ilarischeinin** [comment]
I said earlier that this should be incorporated to both Bioconductor development and release versions, but with the next release being 3 months away, maybe that'll do just fine. I might be the only person who has encountered these bugs anyway.

**Comment by daoud-sie** [comment]
Thanx Ilari, just merged. I will propagate these changes to the Bioconducter development version.

**Pull request merged**
