### PR TITLE
Fixing remaining R CMD check NOTE and bumping package dependencies

### PR DESCRIPTION
**Pull request by HenrikBengtsson**

### CODE REVIEW

**Comment by ilarischeinin** [comment]
After merging this, I got an email that [Travis failed](https://travis-ci.org/ccagc/QDNAseq/builds/130770079):

> Error in file(filename, "r", encoding = encoding) : 
>   internet routines cannot be loaded

I suppose this is a problem on their end? Looks like that to me, and the build did pass after your last included commit.

**Comment by ilarischeinin** [comment]
Never mind. I wasn't logged in to Travis, so the re-run button wasn't there. But it passes now.

**Comment by HenrikBengtsson** [comment]
Yes, Travis CI had some internal issues for a short period. Saw it with other packages too.

Note that my PR was to the develop branch. I guess master need to be too Bioconductor SVN before this one can be merged and brought upstreams.

**Comment by ilarischeinin** [comment]
OK. Yeah I noticed the branch. I have a tiny change waiting that I want to do, and I'll merge to master after that. Daoud is the only one who can push master to Bioconductor's SVN though.

**Pull request merged**
