### PR TITLE
Implement parallel computing

### PR DESCRIPTION
**Pull request by ilarischeinin**
These commits implement parallel computing for `estimateCorrection()` and `segmentBins()`. The number of cores to use is specified via argument `mc.cores`. This works on OS X and Linux, but not on Windows.

Just FYI: I have a couple more PRs coming in the near future, if you'd prefer to wait with pushing things to Bioconductor, and to take care of everything at one go.

Because of the nice speedup provided by parallelization, you guys might like to start using this already in the lab though.

### CODE REVIEW

**Comment by daoud-sie** [comment]
I’ll hold the Bioc push. Looking forward to your PR’s!

**Comment by HenrikBengtsson** [comment]
Please see my comments over at #19.

**Comment by HenrikBengtsson** [comment]
.travis.yml needs to be updated reflecting the pkg dependency changes, hence the current error. On the phone so can't PR easily.

**Comment by ilarischeinin** [comment]
I (hope) I did that already, just waiting for it to run.

(I added `future` after `$RENV install_r` (and removed `snowfall`).)

**Pull request merged**
