### PR TITLE
Now correctly plots segment values above and below ylim)

### PR DESCRIPTION
**Pull request by edk360**

### CODE REVIEW

**Comment by HenrikBengtsson** [comment]
Who's behind @edk360? I'd like to give proper credits in the NEWS file.

**Comment by HenrikBengtsson** [comment]
FYI, this is now part of QDNAseq 1.21.5 that was just ("finally") pushed to [Bioc devel](https://github.com/ccagc/QDNAseq/tree/bioc-devel).

**Comment by edk360** [comment]
> Who's behind @edk360? I'd like to give proper credits in the NEWS file.

My name is Erik van Dijk

**Comment by HenrikBengtsson** [comment]
Thanks, just added you as a contributor (https://github.com/ccagc/QDNAseq/commit/5e9a667255f4b034a914b831a7d5a9545dddc596)

**Pull request merged**
