### PR TITLE
Enabling Travis CI and Coveralls source code coverage

### PR DESCRIPTION
**Pull request by HenrikBengtsson**
This PR enables:
* Travis CI:
 - `R CMD build` and `R CMD check` of the package, e.g. https://travis-ci.org/HenrikBengtsson/QDNAseq/builds/48939471
 - Code coverage of tests by [covr](https://github.com/jimhester/covr), e.g. expand last bullet point in above Travis URL.
* Coveralls:
 - Above 'covr' results are automatically sent to Coveralls for detailed view of code coverage, e.g. https://coveralls.io/jobs/4231050
* Adds status Travis CI and Coveralls badges to README and a link to Bioc devel check results.

The covr/Coveralls feature is outstanding in the sense that it will improve the quality, because I'll bet you big time that the code currently not tested has bugs.  That's just the nature of universe.

What you (=ccagc) need to do:
* Travis CI:
 - Signup/sign-in at https://travis-ci.org/ with your GitHub account.  
 - Go to https://travis-ci.org/profile/ccagc/, sync repositories, and "enable" the QDNAseq repository.
* Coveralls:
 - Signup/sign-in at https://coveralls.io/ with your GitHub account.
 - Go to https://coveralls.io/repos/, sync repositories, and "enable" the QDNAseq repository.

Next time you push something to your GitHub repository, you'll see that Travis CI starts running (https://travis-ci.org/ccagc/QDNAseq/).  QDNAseq has quite a few heavy BioC dependencies so it'll take 10-15 mins to complete the whole process.

### CODE REVIEW

**Comment by HenrikBengtsson** [comment]
FYI, I've now increased the test coverage from 37% to 55%, cf. https://coveralls.io/r/HenrikBengtsson/QDNAseq

**Comment by HenrikBengtsson** [comment]
Thxs. You'll also have to create the Travis and Coveralls accounts, otherwise this merge is moot.

**Comment by daoud-sie** [comment]
Ok, I merged this pull request with the devel branch and master. It should now propagate into bioconductor-devel.

**Comment by HenrikBengtsson** [comment]
Just another bump:

As long as https://travis-ci.org/ccagc/QDNAseq is not enabled (=account
created on Travis), the whole Travis CI config will not kick in.  It's only
the owners of ccagc who can create https://travis-ci.org/ccagc/.

Travis CI is great because it adds a nearly instant 'R CMD check'
validation of every single commit done to GitHub, meaning one doesn't have
to wait the 24-36 hours for the BioC builds/checks to be available.

/H

**Comment by daoud-sie** [comment]
Ok, I think I just enabled it,...

**Comment by HenrikBengtsson** [comment]
Great. Now the badges on

https://github.com/ccagc/QDNAseq/

Show the current R CMD check status and test code coverage. This without
having to wait for Bioc.

Henrik

**Pull request merged**
